swagger: '2.0'
info:
  description: ShipperAPI Documentation
  version: '1.0'
  title: ShipperAPI Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: shipper-controller
    description: Shipper Controller
paths:
  /home:
    get:
      tags:
        - shipper-controller
      summary: home
      operationId: homeUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /shipper:
    get:
      tags:
        - shipper-controller
      summary: getShippers
      operationId: getShippersUsingGET
      produces:
        - '*/*'
      parameters:
        - name: companyApproved
          in: query
          description: companyApproved
          required: false
          type: boolean
        - name: pageNo
          in: query
          description: pageNo
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Shipper'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - shipper-controller
      summary: addShipper
      operationId: addShipperUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: postShipper
          description: postShipper
          required: true
          schema:
            $ref: '#/definitions/PostShipper'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ShipperCreateResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/shipper/{shipperId}':
    get:
      tags:
        - shipper-controller
      summary: getOneShipper
      operationId: getOneShipperUsingGET
      produces:
        - '*/*'
      parameters:
        - name: shipperId
          in: path
          description: shipperId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Shipper'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - shipper-controller
      summary: updateShipper
      operationId: updateShipperUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: shipperId
          in: path
          description: shipperId
          required: true
          type: string
        - in: body
          name: updateShipper
          description: updateShipper
          required: true
          schema:
            $ref: '#/definitions/UpdateShipper'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ShipperUpdateResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - shipper-controller
      summary: deleteShipper
      operationId: deleteShipperUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: shipperId
          in: path
          description: shipperId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ShipperDeleteResponse'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
definitions:
  PostShipper:
    type: object
    properties:
      companyName:
        type: string
      kyc:
        type: string
      phoneNo:
        type: integer
        format: int64
      shipperLocation:
        type: string
      shipperName:
        type: string
    title: PostShipper
  Shipper:
    type: object
    properties:
      accountVerificationInProgress:
        type: boolean
      companyApproved:
        type: boolean
      companyName:
        type: string
      kyc:
        type: string
      phoneNo:
        type: integer
        format: int64
      shipperId:
        type: string
      shipperLocation:
        type: string
      shipperName:
        type: string
    title: Shipper
  ShipperCreateResponse:
    type: object
    properties:
      accountVerificationInProgress:
        type: boolean
      companyApproved:
        type: boolean
      companyName:
        type: string
      kyc:
        type: string
      message:
        type: string
      phoneNo:
        type: integer
        format: int64
      shipperId:
        type: string
      shipperLocation:
        type: string
      shipperName:
        type: string
      status:
        type: string
    title: ShipperCreateResponse
  ShipperDeleteResponse:
    type: object
    properties:
      message:
        type: string
      status:
        type: string
    title: ShipperDeleteResponse
  ShipperUpdateResponse:
    type: object
    properties:
      accountVerificationInProgress:
        type: boolean
      companyApproved:
        type: boolean
      companyName:
        type: string
      kyc:
        type: string
      message:
        type: string
      phoneNo:
        type: integer
        format: int64
      shipperId:
        type: string
      shipperLocation:
        type: string
      shipperName:
        type: string
      status:
        type: string
    title: ShipperUpdateResponse
  UpdateShipper:
    type: object
    properties:
      accountVerificationInProgress:
        type: boolean
      companyApproved:
        type: boolean
      companyName:
        type: string
      kyc:
        type: string
      phoneNo:
        type: integer
        format: int64
      shipperLocation:
        type: string
      shipperName:
        type: string
    title: UpdateShipper
