swagger: '2.0'
info:
  description: TransporterAPI Documentation
  version: '1.0'
  title: TransporterAPI Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:9090'
basePath: /
tags:
  - name: transporter-controller
    description: Transporter Controller
paths:
  /home:
    get:
      tags:
        - transporter-controller
      summary: home
      operationId: homeUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /transporter:
    get:
      tags:
        - transporter-controller
      summary: getTransporters
      operationId: getTransportersUsingGET
      produces:
        - '*/*'
      parameters:
        - name: companyApproved
          in: query
          description: companyApproved
          required: false
          type: boolean
        - name: pageNo
          in: query
          description: pageNo
          required: false
          type: integer
          format: int32
        - name: transporterApproved
          in: query
          description: transporterApproved
          required: false
          type: boolean
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Transporter'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - transporter-controller
      summary: addTransporter
      operationId: addTransporterUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: transporter
          description: transporter
          required: true
          schema:
            $ref: '#/definitions/PostTransporter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TransporterCreateResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/transporter/{transporterId}':
    get:
      tags:
        - transporter-controller
      summary: getOneTransporter
      operationId: getOneTransporterUsingGET
      produces:
        - '*/*'
      parameters:
        - name: transporterId
          in: path
          description: transporterId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Transporter'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - transporter-controller
      summary: updateTransporter
      operationId: updateTransporterUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: transporter
          description: transporter
          required: true
          schema:
            $ref: '#/definitions/UpdateTransporter'
        - name: transporterId
          in: path
          description: transporterId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TransporterUpdateResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - transporter-controller
      summary: deleteTransporter
      operationId: deleteTransporterUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: transporterId
          in: path
          description: transporterId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TransporterDeleteResponse'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
definitions:
  PostTransporter:
    type: object
    properties:
      companyName:
        type: string
      kyc:
        type: string
      phoneNo:
        type: integer
        format: int64
      transporterLocation:
        type: string
      transporterName:
        type: string
    title: PostTransporter
  Transporter:
    type: object
    properties:
      accountVerificationInProgress:
        type: boolean
      companyApproved:
        type: boolean
      companyName:
        type: string
      kyc:
        type: string
      phoneNo:
        type: integer
        format: int64
      transporterApproved:
        type: boolean
      transporterId:
        type: string
      transporterLocation:
        type: string
      transporterName:
        type: string
    title: Transporter
  TransporterCreateResponse:
    type: object
    properties:
      accountVerificationInProgress:
        type: boolean
      companyApproved:
        type: boolean
      companyName:
        type: string
      kyc:
        type: string
      message:
        type: string
      phoneNo:
        type: integer
        format: int64
      status:
        type: string
      transporterApproved:
        type: boolean
      transporterId:
        type: string
      transporterLocation:
        type: string
      transporterName:
        type: string
    title: TransporterCreateResponse
  TransporterDeleteResponse:
    type: object
    properties:
      message:
        type: string
      status:
        type: string
    title: TransporterDeleteResponse
  TransporterUpdateResponse:
    type: object
    properties:
      accountVerificationInProgress:
        type: boolean
      companyApproved:
        type: boolean
      companyName:
        type: string
      kyc:
        type: string
      message:
        type: string
      phoneNo:
        type: integer
        format: int64
      status:
        type: string
      transporterApproved:
        type: boolean
      transporterId:
        type: string
      transporterLocation:
        type: string
      transporterName:
        type: string
    title: TransporterUpdateResponse
  UpdateTransporter:
    type: object
    properties:
      accountVerificationInProgress:
        type: boolean
      companyApproved:
        type: boolean
      companyName:
        type: string
      kyc:
        type: string
      phoneNo:
        type: integer
        format: int64
      transporterApproved:
        type: boolean
      transporterLocation:
        type: string
      transporterName:
        type: string
    title: UpdateTransporter
